/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Khofi Muffin
 */
public class main extends javax.swing.JFrame {
    int pertama;
    int kedua;
    int hasil;
    String operator;
    
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equal = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        but6 = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        but5 = new javax.swing.JButton();
        but0 = new javax.swing.JButton();
        but8 = new javax.swing.JButton();
        but7 = new javax.swing.JButton();
        but9 = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        per = new javax.swing.JButton();
        but1 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        look = new javax.swing.JTextField();
        but3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        equal.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        getContentPane().add(equal);
        equal.setBounds(480, 250, 70, 220);

        but2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        but2.setText("2");
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });
        getContentPane().add(but2);
        but2.setBounds(120, 170, 70, 60);

        but6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        but6.setText("6");
        but6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but6ActionPerformed(evt);
            }
        });
        getContentPane().add(but6);
        but6.setBounds(210, 250, 70, 60);

        but4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        but4.setText("4");
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });
        getContentPane().add(but4);
        but4.setBounds(30, 250, 70, 60);

        but5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        but5.setText("5");
        but5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but5ActionPerformed(evt);
            }
        });
        getContentPane().add(but5);
        but5.setBounds(120, 250, 70, 60);

        but0.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        but0.setText("0");
        but0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but0ActionPerformed(evt);
            }
        });
        getContentPane().add(but0);
        but0.setBounds(30, 410, 250, 60);

        but8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        but8.setText("8");
        but8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but8ActionPerformed(evt);
            }
        });
        getContentPane().add(but8);
        but8.setBounds(120, 330, 70, 60);

        but7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        but7.setText("7");
        but7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but7ActionPerformed(evt);
            }
        });
        getContentPane().add(but7);
        but7.setBounds(30, 330, 70, 60);

        but9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        but9.setText("9");
        but9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but9ActionPerformed(evt);
            }
        });
        getContentPane().add(but9);
        but9.setBounds(210, 330, 70, 60);

        plus.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        getContentPane().add(plus);
        plus.setBounds(300, 170, 160, 60);

        minus.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        getContentPane().add(minus);
        minus.setBounds(300, 250, 160, 60);

        per.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        per.setText("/");
        per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perActionPerformed(evt);
            }
        });
        getContentPane().add(per);
        per.setBounds(300, 410, 160, 60);

        but1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        but1.setText("1");
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });
        getContentPane().add(but1);
        but1.setBounds(30, 170, 70, 60);

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton20.setText("C");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(480, 170, 70, 60);

        multi.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        multi.setText("*");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        getContentPane().add(multi);
        multi.setBounds(300, 330, 160, 60);

        look.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        getContentPane().add(look);
        look.setBounds(30, 30, 520, 120);

        but3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        but3.setText("3");
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });
        getContentPane().add(but3);
        but3.setBounds(210, 170, 70, 60);

        setBounds(0, 0, 595, 539);
    }// </editor-fold>//GEN-END:initComponents

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
        // TODO add your handling code here:
        String Enternumber = look.getText()+but1.getText();
        look.setText(Enternumber);
    }//GEN-LAST:event_but1ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
        // TODO add your handling code here:
        String Enternumber = look.getText()+but2.getText();
        look.setText(Enternumber);
    }//GEN-LAST:event_but2ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
        // TODO add your handling code here:
        String Enternumber = look.getText()+but3.getText();
        look.setText(Enternumber);
    }//GEN-LAST:event_but3ActionPerformed

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
        // TODO add your handling code here:
        String Enternumber = look.getText()+but4.getText();
        look.setText(Enternumber);
    }//GEN-LAST:event_but4ActionPerformed

    private void but5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but5ActionPerformed
        // TODO add your handling code here:
        String Enternumber = look.getText()+but5.getText();
        look.setText(Enternumber);
    }//GEN-LAST:event_but5ActionPerformed

    private void but6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but6ActionPerformed
        // TODO add your handling code here:
        String Enternumber = look.getText()+but6.getText();
        look.setText(Enternumber);
    }//GEN-LAST:event_but6ActionPerformed

    private void but7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but7ActionPerformed
        // TODO add your handling code here:
        String Enternumber = look.getText()+but7.getText();
        look.setText(Enternumber);
    }//GEN-LAST:event_but7ActionPerformed

    private void but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but8ActionPerformed
        // TODO add your handling code here:
        String Enternumber = look.getText()+but8.getText();
        look.setText(Enternumber);
    }//GEN-LAST:event_but8ActionPerformed

    private void but9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but9ActionPerformed
        // TODO add your handling code here:
        String Enternumber = look.getText()+but9.getText();
        look.setText(Enternumber);
    }//GEN-LAST:event_but9ActionPerformed

    private void but0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but0ActionPerformed
        // TODO add your handling code here:
        String Enternumber = look.getText()+but0.getText();
        look.setText(Enternumber);
    }//GEN-LAST:event_but0ActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:    
        pertama = Integer.parseInt(look.getText());
        look.setText("");
        operator = "+";
    }//GEN-LAST:event_plusActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        pertama = Integer.parseInt(look.getText());
        look.setText("");
        operator = "-";
    }//GEN-LAST:event_minusActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        // TODO add your handling code here:
        pertama = Integer.parseInt(look.getText());
        look.setText("");
        operator = "*";
    }//GEN-LAST:event_multiActionPerformed

    private void perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perActionPerformed
        // TODO add your handling code here:
        pertama = Integer.parseInt(look.getText());
        look.setText("");
        operator = "/";
    }//GEN-LAST:event_perActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        look.setText("");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        kedua = Integer.parseInt(look.getText());
        if(operator.equals("+"))
            hasil = pertama + kedua;
        if(operator.equals("-"))
            hasil = pertama + kedua;
        if(operator.equals("*"))
            hasil = pertama + kedua;
        if(operator.equals("/"))
            hasil = pertama + kedua;
        look.setText(hasil+"");
    }//GEN-LAST:event_equalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but0;
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JButton but6;
    private javax.swing.JButton but7;
    private javax.swing.JButton but8;
    private javax.swing.JButton but9;
    private javax.swing.JButton equal;
    private javax.swing.JButton jButton20;
    private javax.swing.JTextField look;
    private javax.swing.JButton minus;
    private javax.swing.JButton multi;
    private javax.swing.JButton per;
    private javax.swing.JButton plus;
    // End of variables declaration//GEN-END:variables
}
